
    export const memberData = [
        {   
            memberId:1,
            memberImage: '/images/new sakthi stephen.png',
            memberName: 'P.G. Sakthi Stephen',
            memberDesignation: 'Proprietor',
            memberSocial: {
            linkedin: '/',
            twitter: '/',
            youtube: '/',
            facebook: '/',
            },
            mainpara : "As a determined young individual, I once faced the challenge of showcasing my talents without any support or encouragement. This experience ignited a fire within me, fueling a passion to pave the way for others facing similar challenges. As the leader of a dedicated group of Assiduous people, we have boldly launched D25 with a clear vision: to provide a platform and opportunities for those who are determined to leav their mark and prove their worth.",
            subpara : "It all started with a Dreamer who sought to empower individuals like you to become Dreammakers. Embrace your potential and join us in turning dreams into reality.",
        },
        {
            memberId:2,
            memberImage: '/images/new kalpana.png',
            memberName: 'Kalpana Stephen',
            memberDesignation: 'Chief Executive',
            memberSocial: {
            linkedin: '/',
            twitter: '/',
            youtube: '/',
            facebook: '/',
            },
            mainpara : "I began my journey in the industry as an ordinary girl. The transition from fear and anxiety to triumph is a testament to the strength of the feminine spirit, and the paths I chose enabled me to overcome all obstacles. I am dedicated to using my platform to inspire and empower others like me.",
            subpara : "The D25 initiative stands as a beacon of hope for women who may feel confined in the role of a housewife, demonstrating that there are opportunities to break free from self-imposed limitations and showcase their talents. Let's unite as a powerful force to uplift and support one another on our path to success.",
        },
        {
        memberId:3,
        memberImage: '/images/JOSHUA GIFTSON.png',
        memberName: 'Joshua Giftson',
        memberDesignation: 'Associate Producer',
        memberSocial: {
          linkedin: '/',
          twitter: '/',
          youtube: '/',
          facebook: '/',
        },
        mainpara : "I am a passionate and inventive media head with over a decade of experience,since 2009. My collaborative nature has allowed me to work with numerous renowned gospel and non-governmental organizations as a graphic designer and photographer. This has led me to work onsite in 20+ countries and offsite for clients from the UK, USA, and Germany.",
        subpara : "My Voyage has now brought me to D25, where I am excited to join forces with P.G. Shakthi Stephen and a pack of like-minded individuals. Together, we are embarking on a new adventure filled with creativity and vision.",
      },
      {
        memberId:4,
        memberImage: '/images/JENEFER JOSABATH.png',
        memberName: 'Jenefer Josabath',
        memberDesignation: 'Associate Executive',
        memberSocial: {
          linkedin: '/',
          twitter: '/',
          youtube: '/',
          facebook: '/',
        },
        mainpara : "With a philanthropic motive and driven by an intuition to embark on this journey of uplifting, I have become a part of D25. Working with individuals of diverse backgrounds and engaging in intrapersonal learning has enhanced my dextrous capabilities. In this house, hierarchy is non-existent, and valuable insights can be gained regardless of age or proficiency.",
        subpara : "If you are aspiring to join us on this exciting journey, you may encounter me at various points. Please do not hesitate to wave a “Hi !”. Your kind gesture will brighten our day a little more.",
      },
      {
        memberId:5,
        memberImage: '/images/MAXELL RODRIGUES.png',
        memberName: 'Maxell Rodrigues',
        memberDesignation: 'Associate Director',
        memberSocial: {
          linkedin: '/',
          twitter: '/',
          youtube: '/',
          facebook: '/',
        },
        mainpara : "My journey in the creative world started as a Graphic Designer, digital artist and show producer, but I didn't settle there. I ventured into UI/UX Design and development, and took up leadership roles in various innovative projects. Fuelled by my passion, I constantly seek new ideas and strive to enhance my skills, leading to successful collaborations on diverse projects and adept problem-solving. Being a good listener is essential in my approach.",
        subpara : "The advent of project D25 represents a long-awaited fulfillment of my aspirations. This endeavorallows me to showcase the culmination of my years of skill development in a manner that isuniquely mine and at a pace I dictate. It presents an opportunity for me to unleash the latent talents that have long been yearning to be expressed.",
      },
      {
        memberId:6,
        memberImage: '/images/NANDHINI G.png',
        memberName: 'Nandhini',
        memberDesignation: 'Assistant Director',
        memberSocial: {
          linkedin: '/',
          twitter: '/',
          youtube: '/',
          facebook: '/',
        },
        mainpara : "As a passionate visual designer and digital artist. I believe that design is more than just about aesthetics. It has the power to evoke emotions and establish deep, meaningful connections. With over 7 years of experience and a keen ability for active listening, I have collaborated with clients across diverse industries, bringing a unique blend of creativity and strategic thinking to every endeavor.",
        subpara : "The inception of D25 marks the realization of my long-held dreams and ambitions, where we can unleash our vision and flourish without boundaries. And I am thrilled to embark on this new journey with both passion and compassion, aspiring for growth together.",
      },
      {
        memberId:7,
        memberImage: '/images/Jenniffer Steffy.png',
        memberName: 'Jeniffer Steffy',
        memberDesignation: 'Content Writer',
        memberSocial: {
          linkedin: '/',
          twitter: '/',
          youtube: '/',
          facebook: '/',
        },
        mainpara : "A content writer is a skilled professional adept at crafting engaging and informative text tailored to a variety of audiences. Their expertise spans across multiple formats, including blog posts, articles, website content, and social media updates. By conducting thorough research and understanding the nuances of target demographics, content writers create compelling narratives that not only inform but also captivate readers. ",
        subpara : "Their work is crucial in establishing brand voice, driving web traffic, and fostering customer engagement.",
      },
      {
        memberId:8,
        memberImage: '/images/JOHN MERVIN.png',
        memberName: 'John Mervin',
        memberDesignation: 'Associate content Writer',
        memberSocial: {
          linkedin: '/',
          twitter: '/',
          youtube: '/',
          facebook: '/',
        },
        mainpara : "“There is no greater agony than bearing an untold story inside you.” — says Maya Angelou. This drives me to unearth the untold stories through writing. As an aspiring writer, I am dedicated to giving my all in every piece I create, aiming to convey kindness and compassion for humanity in a direct and impactful manner, No greys in between.",
        subpara : "Joining this organization aligns perfectly with my core values, marking a new chapter in mycareer. I am ready to dive into the depths of the sea and reach for the heights of the horizon, embracing the challenges and opportunities that lie ahead.",
      },
     
]